### ISSUE TITLE
Hangs due to duplication of posts on metadata

### ISSUE THREAD

**Issue by iwootten** [totocaster/metalsmith-tags#19]
Using the recent 0.10 release in my metalsmith chain still leads to the above problem. It seems that the overall killer is [L120](https://github.com/totocaster/metalsmith-tags/blob/master/lib/index.js#L120), which leads to a large amount of posts getting duplicated in memory on the metadata object for each and every tag on a post. 

For the last decades worth of tags/posts I have, metalsmith-tags hangs with no error output. Given I'm not using that object to my knowledge - commenting out that line does solve the issue whilst still generating the html I need. It will no longer pass tests, but could prove a workable solution for those experiencing slow/hanging issues if they don't use it later in their chain.

**Comment by hswolff** [comment]
Yeah, that unfortunately is going to always be the case, just due to how metalsmith works.

I ran into a similar issue in the past where metadata was causing metalsmith to break and it ended up being a malformed post that was causing things to go haywire.

Whatever the case I added a new option to metalsmith-tags `skipMetadata` that does exactly what's described - allows skipping the updating of the metadata object. Right now it defaults to false so just turn it on like in the examples shown in the updated `README.md` file and you should be good to go.

**Comment by iwootten** [comment]
Thanks @hswolff - I'll check this out later.
